<a href="https://colab.research.google.com/github/BrokenSpirits/Python-Programming/blob/Add-On-Course-JECC/Numpy(07_01_22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
t=lambda var:var**2

In [ ]:
t(5)

25

In [ ]:
seq=[1,2,4,6,8]

In [ ]:
list(map(lambda num:num**3,seq))

[1, 8, 64, 216, 512]

In [ ]:
list(filter(lambda num:num%2==0,seq))

[2, 4, 6, 8]

In [ ]:
#Methods

In [ ]:
s='hello my name is Pappadapappachan'

In [ ]:
s.upper()


'HELLO MY NAME IS PAPPADAPAPPACHAN'

In [ ]:
s.split()


['hello', 'my', 'name', 'is', 'Pappadapappachan']

In [ ]:
tweet = 'Go Sports! #Sports'

In [ ]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [ ]:
list=[1,2,3]

In [ ]:
list.pop()


3

In [ ]:
first=list.pop(0)

In [ ]:
first

1

In [ ]:
x=[(2,3),(4,5),(6,7)]

In [ ]:
x[0]

(2, 3)

In [ ]:
x[0][1]

3

In [ ]:
#Python Data Analysis Library - Numpy

In [ ]:
array=([1,2,3])

In [ ]:
my_mat=([1,2,3],[4,5,6],[7,8,9])

In [ ]:
import numpy as np

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.randn(2) #Standard Normal Distribution

array([-0.97349264,  0.92047791])

In [ ]:
np.random.randint(1,100)

14

In [ ]:
np.random.randint(1,100,10)

array([31,  4, 63,  1, 72, 91, 34, 73, 62,  8])

In [ ]:
arr=np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])