<a href="https://colab.research.google.com/github/BrokenSpirits/Python-Programming/blob/Add-On-Course-JECC/Numpy_cont(20_01_22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy Arrays

In [2]:
my_list = [1,23,34]

In [4]:
import numpy as np
arr=np.array(my_list)

In [5]:
arr

array([ 1, 23, 34])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10) #equally spaced point ID Array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [18]:
np.eye(4) #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.1936394 , 0.34751753, 0.44876808, 0.39196181, 0.25672878])

In [20]:
np.random.rand(5,5)

array([[0.15140266, 0.15215391, 0.96781864, 0.57262805, 0.30609565],
       [0.63950068, 0.77603441, 0.11668376, 0.59277899, 0.56649527],
       [0.73637206, 0.07200822, 0.97038303, 0.28531953, 0.06590353],
       [0.82133567, 0.70043065, 0.23705703, 0.7755968 , 0.45375512],
       [0.53041472, 0.73210413, 0.88698532, 0.58288909, 0.85772157]])

In [22]:
np.random.randn(3) #standard normal distribution

array([ 0.8339827 , -1.05162968, -0.54793661])

In [23]:
np.random.randint(1,100)

28

In [24]:
np.random.randint(1,100,10)

array([24, 66, 13, 61, 83, 72, 20,  4, 50, 73])

In [25]:
arr=np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr=np.random.randint(0,50,10)

In [28]:
ranarr

array([43, 15, 27, 15, 49, 39, 33,  4, 10, 16])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

49

In [31]:
ranarr.min()

4

In [32]:
ranarr.argmax() #Index of Max Value

4

In [33]:
ranarr.argmin() #Index of Min Value

7

In [34]:
arr.shape

(25,)

In [38]:
arr1=arr.reshape(5,5) #Converting 1D to 2D Array

In [39]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr1.shape

(5, 5)

In [41]:
arr.dtype

dtype('int64')

In [42]:
from numpy.random import randint
randint(2,10)

7

In [43]:
#Numpy Indexing & Selection

In [44]:
arr[8]

8

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[0:5]=100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [51]:
arr2=arr[0:8]

In [52]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7])

In [53]:
arr2[:]=99

In [54]:
arr2

array([99, 99, 99, 99, 99, 99, 99, 99])

In [55]:
arr_copy=arr[0:6]

In [56]:
arr_copy

array([99, 99, 99, 99, 99, 99])

In [57]:
arr_copy=arr.copy()

In [58]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr_2d=np.array([[5,10,15],[20,25,30],[40,45,50]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

In [64]:
arr_2d[0]


array([ 5, 10, 15])

In [65]:
arr_2d[0][2]

15

In [66]:
arr_2d[2][1]

45

In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr >20

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True])

In [70]:
bool_arr=arr>20

In [71]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True])

In [72]:
arr[arr<10]

array([8, 9])

In [75]:
arr1_2d=np.arange(50).reshape(5,10)

In [77]:
arr1_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [78]:
arr1_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [79]:
arr1_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])